### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by megalucio**
` not needed

### CODE REVIEW

**Comment by megalucio** [comment]
` not needed

**Comment by jkuri** [comment]
hi @megalucio, thanks! why did you close your PR?

**Comment by megalucio** [comment]
Hi there.

Well, I was not quite sure what I was doing as I do not have experience
with pull requests and was quite in a hurry. And I suppose it was not worth
it for a just a `.

Cheers,

Ignacio Íñigo

**Comment by megalucio** [comment]
Sorry, reopened it...

**Pull request merged**
