### PR TITLE
Duplicate upload fix, expose response status, and expose FormData object

### PR DESCRIPTION
**Pull request by oleosjo**

### CODE REVIEW

**Comment by jkuri** [comment]
hi Jonathan. thanks for this PR. can you please update README.md and bump version in `package.json` so I can get this published after merge. thanks.

**Comment by oleosjo** [comment]
Hello. I updated the Readme and advanced the version. I also realized I was basing my code off of 3.3.6, so I updated it to 3.3.7.

**Comment by oleosjo** [comment]
Let me know if you'd rather me cherry pick and separate these 3 issues

**Comment by jkuri** [comment]
published to `npm`. thanks!

**Comment by oleosjo** [comment]
Cool, thanks!

**Pull request merged**
