### PR TITLE
Fixed DragEvent on Safari and other browsers that don't support this …

### PR DESCRIPTION
**Pull request by BenevidesLecontes**
It seems that, Safari don't support DragEvent, neither PhantomJS.

### CODE REVIEW

**Comment by adrian-mitangi** [comment]
I've encountered this issue as well on safari.

Please make this a priority to fix the conflicts and merge.

**Comment by jkuri** [comment]
@BenevidesLecontes can you rebase your PR please?

**Comment by BenevidesLecontes** [comment]
@jkuri done! Test and let me know if it works.

**Comment by jkuri** [comment]
looks alright, thanks!

**Pull request merged**
